image:
  file: Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5090
    onOpen: ignore
tasks:
  - init: |
      eval $(command gp env -e)
      cd /workspace && curl -o bftools.zip \
        https://downloads.openmicroscopy.org/bio-formats/6.10.0/artifacts/bftools.zip && \
        unzip bftools.zip && rm bftools.zip
      python -m synapseclient -u "$SYN_USER" -p "$SYN_TOKEN" \
        get --downloadLocation /workspace/exemplar-001/ syn31549454 && \
        cd /workspace/exemplar-001/ && \
        unzip exemplar-001.zip && rm exemplar-001.zip
    command: python test.py
